#!/bin/bash

# on pandoc/latex emoji seem to not be installed :(
# runnig with
#   --include-in-header="scripts/header.tex" \
# produces 
#   ! LaTeX Error: File `xelatexemoji.sty' not found.

docker run --rm --volume "$(pwd):/data" --user `id -u`:`id -g` pandoc/latex \
  --pdf-engine=xelatex --mathjax \
  --highlight-style zenburn \
  --resource-path .:./$(dirname $1):./static \
  "$1" -o "$2"
