#!/bin/bash

docker run --rm -u `id -u`:`id -g` \
  --mount "type=bind,src=$(pwd),dst=/pandoc" \
  pandocker \
  -f markdown \
  --resource-path .:./$(dirname $1):./static \
  --include-in-header="scripts/tex/header.tex" \
  --pdf-engine=xelatex --mathjax \
  --highlight-style zenburn \
  --resource-path .:./$(dirname $1):./static \
  "$1" -o "$2"
